### ISSUE TITLE
Uncaught Error shown on homepage

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-show-affiliate-coupons#26]
### Expected behavior
When I activate Show Affiliate Coupons, I expect everything to work as designed.

### Actual behavior
A [customer sent in a ticket](https://secure.helpscout.net/conversation/1060773146/143375?folderId=634609) with the following:
>When I enable your plugin, i get this error on the front end:

```
Uncaught Error: Call to undefined function wc_get_coupon_type() in /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php on line 472
get_coupons()
wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php:382
no_access()
wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php:300
register_tab()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/plugin.php:206
apply_filters()
wp-content/plugins/affiliate-wp/includes/affiliate-functions.php:1709
affwp_get_affiliate_area_tabs()
wp-content/plugins/affiliate-wp/includes/affiliate-functions.php:1725
affwp_get_active_affiliate_area_tab()
wp-content/plugins/affiliate-wp/includes/scripts.php:167
affwp_frontend_scripts_and_styles()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/class-wp-hook.php:312
do_action()
wp-includes/plugin.php:478
do_action()
wp-includes/script-loader.php:2670
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/class-wp-hook.php:312
do_action()
wp-includes/plugin.php:478
do_action()
wp-includes/general-template.php:2879
wp_head()
wp-content/themes/Avada/header.php:21
require_once()
wp-includes/template.php:722
load_template()
wp-includes/template.php:671
locate_template()
wp-includes/general-template.php:41
get_header()
wp-content/themes/Avada/page.php:14
include()
wp-includes/template-loader.php:98
require_once()
wp-blog-header.php:19
require()
index.php:17
There has been a critical error on your website.
```

I sent the following reply to the customer: 
>I was not able to see the error using the same type of set up as you on a testing site (using the same version of AffiliateWP, WordPress, and PHP). Are you seeing this error on every page when Show Affiliate Coupons is active? Did this error show up recently after making an update? 

The customer replied:
>Thank you for your response.

>It happened after updating these plugins:

>- Duplicator Pro
>- WP File Manager
>- Master Popups

>I have tested by disabling these plugins and the error still shows.

>The error only shows while logged in as admin and only on the home page.

>I'm attaching the most recent error log.

```    
>[21-Jan-2020 21:34:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_coupon_type() in /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php:472
Stack trace:
#0 /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php(382): AffiliateWP_Show_Affiliate_Coupons->get_coupons()
#1 /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php(300): AffiliateWP_Show_Affiliate_Coupons->no_access()
#2 /home/jakubsnm/public_html/bdsmcontracts.org/wp-includes/class-wp-hook.php(288): AffiliateWP_Show_Affiliate_Coupons->register_tab(Array)
#3 /home/jakubsnm/public_html/bdsmcontracts.org/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#4 /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/affiliate-wp/includes/affiliate-functions.php(1709): apply_filters('affwp_affiliate...',  in /home/jakubsnm/public_html/bdsmcontracts.org/wp-content/plugins/query-monitor/collectors/php_errors.php on line 82
```

### Steps to reproduce the behavior 
1) I was not able to replicate this problem, but this is happening for the customer when the Show Affiliate Coupons add-on is active the error only shows while logged in as admin and only on the home page. 

### Information 
PHP Version: 7.3.13
AffiliateWP Version: 2.4.3
AffiliateWP - Show Affiliate Coupons: 1.0.7
WordPress Version: 5.3.2

Any other relevant information:
They have temporarily deactivated the Show Affiliate Coupons add-on for the time being.

**Comment by amdrew** [comment]
I can replicate the same error by:

1. Having a tracked affiliate coupon active for my affiliate
2. Enabling WooCommerce as an integration
3. Deactivating the WooCommerce plugin
4. Viewing the front-end as the affiliate

```php
PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_coupon_type() in /wp-content/plugins/affiliatewp-show-affiliate-coupons/affiliatewp-show-affiliate-coupons.php:472
```

The error most likely occurred because:

1. They deactivated WooCommerce temporarily, or
2. One of the plugins they listed temporarily caused WooCommerce to deactivate, or
3. They updated WooCommerce within the admin which would have caused it to become deactivated for a fraction of time

We should add a `function_exists()` call or otherwise check that WooCommerce is active beforehand.

**Comment by michaelbeil** [comment]
I can replicate the error with the above steps, but it doesn't happen when WooCommerce is active. 

The customer asked: 
>Just wondering if you have an update on this?

I let them know that we will look into addressing this in the future.
